spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: qwe123
    testWhileIdle: true
    url: jdbc:mariadb://127.0.0.1:3307/transportador
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: true
